### PR TITLE
request: replace node-fetch for isomorphic-fetch

### PR DESCRIPTION
**Pull request by MarcoWorms**
Node fetch was a problem when targeting for web in webpack. Changing to isomorphic-fetch fixed the issue. Even though this fix is working, we could refactor the request.js to use node built-in http.

### CODE REVIEW

**Comment by MarcoWorms** [comment]
@derekstavis I think your gitcop is somehow screwing travis

**Comment by derekstavis** [comment]
@MarcoWorms you could also use the same body you used in pull request instead of using a dot... It makes a lot more sense.

**Comment by MarcoWorms** [comment]
@derekstavis let's :shipit:?

**Comment by derekstavis** [comment]
@MarcoWorms I'd like to release the next version fixing the bundle size, so I'd prefer implementing `request.js` using native `http` package.

**Pull request merged**
