### PR TITLE
General code improvements

### PR DESCRIPTION
**Pull request by haskellcamargo**
## Description

General code improvements.

- Remove boilerplate from `cardNumber`
- Use Bluebird 3 `catch` on `encryption`

## Goals

- :white_check_mark: linter is passing
- :white_check_mark: tests are passing
- :white_check_mark: @GitCop no longer being mad

This time I'll not be git-copped!

### CODE REVIEW

**Comment by GitCop** [comment]
We found issues in commit naming convention

 * Commit: 941bdd484ddc115da4368a1ec433fee68fe92fa8
  * Bons títulos tem no máximo até 50 caracteres. Para adicionar mais detalhes use o corpo!

O guia completo de estilo de commits está disponível em https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
We found issues in commit naming convention

 * Commit: 941bdd484ddc115da4368a1ec433fee68fe92fa8
  * Bons títulos tem no máximo até 50 caracteres. Para adicionar mais detalhes use o corpo!

O guia completo de estilo de commits está disponível em https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
We found issues in commit naming convention

 * Commit: 73a3d824aa98470fb3d46c14fc47016f87b02bff
  * Bons títulos tem no máximo até 50 caracteres. Para adicionar mais detalhes use o corpo!

O guia completo de estilo de commits está disponível em https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
We found issues in commit naming convention

 * Commit: 73a3d824aa98470fb3d46c14fc47016f87b02bff
  * Bons títulos tem no máximo até 50 caracteres. Para adicionar mais detalhes use o corpo!

O guia completo de estilo de commits está disponível em https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

**Comment by cuchi** [comment]
Nice :)

**Comment by derekstavis** [comment]
Awesome @haskellcamargo, thanks a lot for the improvements and sorry for the delay in merging!!

**Pull request merged**
