### PR TITLE
Fix CPF validation logic

### LINKED ISSUE #194: Validação de CPF/CNPJ com digito verificador 0 não esta funcionando
Estou usando a lib via Browser (Global Variable) com o seguinte import:

`<script src="https://assets.pagar.me/pagarme-js/4.4/pagarme.min.js" />`

Utilizo o seguinte comando para validar os CPF:
`pagarme.validate({cpf: "425.385.450-80"})`

E para os CNPJ:
`pagarme.validate({cnpj: "78.035.718/0001-00"})`

O problema ocorre quando o CPF ou CNPJ contem o digito 0 no digito verificador, como nos exemplos abaixo, nessas situações a validação esta retornando como invalido. 
Porem o meu próprio CPF termina em 00 então isso é uma situação valida.

image

### PR DESCRIPTION
**Pull request by chuttam**
## Description

Previous logic didn't account for the 1st check digit result being exactly `10`.

According to spec, the result of the `modulo(11)` operation should be set to `0` if it results in a `10`, before adding re-applying the mask multipliers for the second pass (including with the new `0` at the end of the numbers list).

Fixes #194

### CODE REVIEW

**Comment by GitCop** [comment]
There are some issues with your commit and our naming convention

 * Commit: 2560d8acc3ab498ef624db1e95155707eb11367a
  * Don't use more than 72 characters per line in the body of your commit. If you reach this limit at the same line, just break and continue at next line. To separate paragraphs, leave a blank line between them.
  * Commits must be in the following format: **%{context}: %{description}**

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There are some issues with your commit and our naming convention

 * Commit: 2560d8acc3ab498ef624db1e95155707eb11367a
  * Don't use more than 72 characters per line in the body of your commit. If you reach this limit at the same line, just break and continue at next line. To separate paragraphs, leave a blank line between them.
  * Commits must be in the following format: **%{context}: %{description}**

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

**Comment by chuttam** [comment]
Fixed GitCop issues.

**Comment by chuttam** [comment]
Any love for this PR? Pinging @zignd (recent merge) to advise who best to add as reviewers? 🤞

**Review by matheusvellone — APPROVED** [review]

**Review by murilohns — APPROVED** [review]

**Review by michaelfidelis — APPROVED** [review]

**Review by isaiasvallejos — APPROVED** [review]

**Review by zignd — APPROVED** [review]

**Comment by lucianopf** [comment]
@chuttam thanks so much for the contribution and all reviewers for the engagement at this PR. ❤️ 🚀 
We're currently at deployment freeze for the black friday. 😢 
Would you mind if we postpone the merge and publish of this change till december? 🙏

**Comment by chuttam** [comment]
@lucianopf No problem at all. We're running our own JS bundle from a fork with this fix anyway.

**Comment by chuttam** [comment]
Thanks for merging!

* I don't have access to look at the failing tests. Are these failures from this PR, or work that was merged in?
* Will there be a notification or some way of knowing when this change gets released as a published JS bundle?

**Pull request merged**
