### PR TITLE
Permite enviar parâmetros na busca por transações de assinaturas

### PR DESCRIPTION
**Pull request by murilohns**
## Description

Resolve o problema da issue https://github.com/pagarme/pagarme-js/issues/269

Com essa alteração será possível enviar os parâmetros `count` e `page` na rota `subscriptions/:id/transactions`

Dúvida: Preciso commitar os arquivos alterados com `yarn build`?

## Your checklist for this pull request

:rotating_light: Please review this items for a good pull request. :four_leaf_clover:

1. I've read the project's [Contributing Guidelines](CONTRIBUTING.md)
1. My commits are well written and follow [pagarme/git-style-guide](https://github.com/pagarme/git-style-guide)
1. My changes are well covered by **tests** and **logs**
1. I've updated the project docs (if needed)
1. I fell safe about this implementation

In a good pull request, everything above is true :relaxed:

### CODE REVIEW

**Comment by GitCop** [comment]
There are some issues with your commit and our naming convention

 * Commit: 1f15a9aa7a3314f6a7063e816504d544b847f26a
  * Commits must be in the following format: **%{context}: %{description}**

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There are some issues with your commit and our naming convention

 * Commit: 1f15a9aa7a3314f6a7063e816504d544b847f26a
  * Commits must be in the following format: **%{context}: %{description}**

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There are some issues with your commit and our naming convention

 * Commit: 1f15a9aa7a3314f6a7063e816504d544b847f26a
  * Commits must be in the following format: **%{context}: %{description}**

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There are some issues with your commit and our naming convention

 * Commit: 1f15a9aa7a3314f6a7063e816504d544b847f26a
  * Commits must be in the following format: **%{context}: %{description}**

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There are some issues with your commit and our naming convention

 * Commit: 262178e546eea454f0e840c9245db95ac2beb81d
  * Commits must be in the following format: **%{context}: %{description}**

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There are some issues with your commit and our naming convention

 * Commit: 262178e546eea454f0e840c9245db95ac2beb81d
  * Commits must be in the following format: **%{context}: %{description}**

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

**Review by zignd — APPROVED** [review]

**Review by edumoreira1506 — APPROVED** [review]

**Pull request merged**
