### PR TITLE
[FCRED-444] Adicionar rotas de KYC da API de Banking

### PR DESCRIPTION
**Pull request by Cahlico**
## Description

Este PR tem como objetivo adicionar as rotas da API de Banking.

Resumo dos endpoints: 

| Rota |  Descrição | 
|---|---|
| `GET /recipients/:recipientId/upgrade` | Obtem detalhes do _KYC_ da conta do recebedor | 
| `POST /recipients/:recipientId/upgrade` | Inicia o processo de _KYC_ para upgrade da conta do recebedor |
| `PUT /recipients/:recipientId/upgrade` | Edita os dados cadastrados do usuário e/ou da _company_ para o _KYC_ |
| `POST /recipients/:recipientId/upgrade/identity` | Gera o QR Code para o processo de captura de fotos dos documentos |

## Your checklist for this pull request

:rotating_light: Please review this items for a good pull request. :four_leaf_clover:

1. I've read the project's [Contributing Guidelines](CONTRIBUTING.md)
1. My commits are well written and follow [pagarme/git-style-guide](https://github.com/pagarme/git-style-guide)
1. My changes are well covered by **tests** and **logs**
1. I've updated the project docs (if needed)
1. I fell safe about this implementation

In a good pull request, everything above is true :relaxed:

### CODE REVIEW

**Comment by GitCop** [comment]
There are some issues with your commit and our naming convention

 * Commit: ef48487eb5e42dc7685d905d6dedcc3d59f921c5
  * Commits must be in the following format: **%{context}: %{description}**

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There are some issues with your commit and our naming convention

 * Commit: ef48487eb5e42dc7685d905d6dedcc3d59f921c5
  * Commits must be in the following format: **%{context}: %{description}**

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There are some issues with your commit and our naming convention

 * Commit: 9db0d82ee9fca22b1aa62716ad3783c1bc47ca6c
  * Commits must be in the following format: **%{context}: %{description}**

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There are some issues with your commit and our naming convention

 * Commit: 9db0d82ee9fca22b1aa62716ad3783c1bc47ca6c
  * Commits must be in the following format: **%{context}: %{description}**

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

**Review by isaiasvallejos — APPROVED** [review]

**Review by emillysandy — APPROVED** [review]

**Pull request merged**
